# config/routes/nelmio_api_doc.yaml
nelmio_api_doc:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger
nelmio_api_doc_ui:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui