nelmio_api_doc:
    documentation:
        info:
            title: 'API RNZStorage'
            description: 'Dokumentacja REST API'
            version: '1.0.0'
    areas:
        default:
            path_patterns: [ ^/api ]
