security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        person_provider:
            entity:
                class: App\Entity\Person
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: person_provider
            custom_authenticator: App\Security\PersonAuthenticator
            json_login:
                check_path: /api/person/login
                username_path: mail
                password_path: haslo

            logout:
                path: /api/person/logout
                invalidate_session: true
                clear_site_data: ["cookies"]

            stateless: false

    access_control:
        - { path: ^/api/person/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/person/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
