parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.entity_manager'
