services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.entity_manager'

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.user_password_hasher'
        public: true
