<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250331062533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE quote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company INT NOT NULL, dodatkowe_informacje TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, data_wystawienia TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_poczatek DATE NOT NULL, data_koniec DATE NOT NULL, dane_kontaktowe TEXT NOT NULL, miejsce TEXT NOT NULL, rabat NUMERIC(5, 2) NOT NULL, PRIMARY KEY(id))
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE quote
        SQL);
    }
}
