<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250528094210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE quote_date (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, value VARCHAR(100) NOT NULL, comment VARCHAR(255) DEFAULT NULL, quote_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_387968F0DB805178 ON quote_date (quote_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE quote_table (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, discount NUMERIC(5, 2) NOT NULL, quote_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_FBD60227DB805178 ON quote_table (quote_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE quote_table_equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, count INT NOT NULL, days INT NOT NULL, discount NUMERIC(5, 2) NOT NULL, show_comment BOOLEAN NOT NULL, quote_table_id INT NOT NULL, equipment_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_BBD855096C580CD ON quote_table_equipment (quote_table_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_BBD85509517FE9FE ON quote_table_equipment (equipment_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_date ADD CONSTRAINT FK_387968F0DB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_table ADD CONSTRAINT FK_FBD60227DB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_table_equipment ADD CONSTRAINT FK_BBD855096C580CD FOREIGN KEY (quote_table_id) REFERENCES quote_table (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_table_equipment ADD CONSTRAINT FK_BBD85509517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_equipment DROP CONSTRAINT fk_54da4cf97cb588e9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_equipment DROP CONSTRAINT fk_54da4cf92fd2fed5
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE quote_equipment
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD projekt VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD lokalizacja VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP dodatkowe_informacje
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP data_poczatek
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP data_koniec
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP dane_kontaktowe
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP miejsce
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote RENAME COLUMN rabat TO global_discount
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ALTER global_discount TYPE NUMERIC(5, 2)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote RENAME COLUMN company TO company_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF4979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B71CBF4979B1AD6 ON quote (company_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE quote_equipment (ilosc INT NOT NULL, rabat NUMERIC(5, 2) NOT NULL, idquote INT NOT NULL, idequipment INT NOT NULL, PRIMARY KEY(idquote, idequipment))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_54da4cf92fd2fed5 ON quote_equipment (idequipment)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_54da4cf97cb588e9 ON quote_equipment (idquote)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_equipment ADD CONSTRAINT fk_54da4cf97cb588e9 FOREIGN KEY (idquote) REFERENCES quote (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_equipment ADD CONSTRAINT fk_54da4cf92fd2fed5 FOREIGN KEY (idequipment) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_date DROP CONSTRAINT FK_387968F0DB805178
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_table DROP CONSTRAINT FK_FBD60227DB805178
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_table_equipment DROP CONSTRAINT FK_BBD855096C580CD
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote_table_equipment DROP CONSTRAINT FK_BBD85509517FE9FE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE quote_date
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE quote_table
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE quote_table_equipment
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF4979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_6B71CBF4979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD dodatkowe_informacje TEXT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD data_poczatek DATE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD data_koniec DATE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD dane_kontaktowe TEXT NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ADD miejsce TEXT NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP projekt
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote DROP lokalizacja
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote RENAME COLUMN company_id TO company
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote RENAME COLUMN global_discount TO rabat
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quote ALTER rabat TYPE NUMERIC(5, 2)
        SQL);
    }
}
