<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250330175336 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP SEQUENCE osoby_idosoba_seq CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            DROP SEQUENCE firma_idfirma_seq CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            DROP SEQUENCE kategoria_idkategoria_seq CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            DROP SEQUENCE magazyn_idsprzet_seq CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            DROP SEQUENCE wycena_idwycena_seq CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE equipment (idsprzet INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nazwa VARCHAR(100) NOT NULL, opis TEXT DEFAULT NULL, ilosc INT NOT NULL, cena NUMERIC(10, 2) NOT NULL, idkategoria INT DEFAULT NULL, PRIMARY KEY(idsprzet))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE wycena DROP CONSTRAINT wycena_idfirma_fkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE wycenasprzet DROP CONSTRAINT wycenasprzet_idwycena_fkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE wycenasprzet DROP CONSTRAINT wycenasprzet_idsprzet_fkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE magazyn DROP CONSTRAINT magazyn_idkategoria_fkey
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE wycena
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE firma
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE wycenasprzet
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE kategoria
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE magazyn
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE osoby
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE SEQUENCE osoby_idosoba_seq INCREMENT BY 1 MINVALUE 1 START 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE SEQUENCE firma_idfirma_seq INCREMENT BY 1 MINVALUE 1 START 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE SEQUENCE kategoria_idkategoria_seq INCREMENT BY 1 MINVALUE 1 START 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE SEQUENCE magazyn_idsprzet_seq INCREMENT BY 1 MINVALUE 1 START 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE SEQUENCE wycena_idwycena_seq INCREMENT BY 1 MINVALUE 1 START 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE wycena (idwycena INT DEFAULT wycena_idwycena_seq NOT NULL, idfirma INT DEFAULT NULL, dodatkoweinformacje TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, datawystawienia TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, datapoczatek DATE NOT NULL, datakoniec DATE NOT NULL, danekontaktowe TEXT NOT NULL, miejsce TEXT NOT NULL, rabat NUMERIC(5, 2) DEFAULT '0', PRIMARY KEY(idwycena))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F56358A5FDE8597A ON wycena (idfirma)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE firma (idfirma INT DEFAULT firma_idfirma_seq NOT NULL, nazwa VARCHAR(100) NOT NULL, nip VARCHAR(15) NOT NULL, adres TEXT NOT NULL, telefon VARCHAR(20) NOT NULL, PRIMARY KEY(idfirma))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX firma_nip_key ON firma (nip)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE wycenasprzet (idwycena INT NOT NULL, idsprzet INT NOT NULL, ilosc INT NOT NULL, rabat NUMERIC(5, 2) DEFAULT '0', PRIMARY KEY(idwycena, idsprzet))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C93A7CD491DEF509 ON wycenasprzet (idwycena)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C93A7CD476A93CF9 ON wycenasprzet (idsprzet)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE kategoria (idkategoria INT DEFAULT kategoria_idkategoria_seq NOT NULL, nazwa VARCHAR(100) NOT NULL, PRIMARY KEY(idkategoria))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE magazyn (idsprzet INT DEFAULT magazyn_idsprzet_seq NOT NULL, nazwa VARCHAR(100) NOT NULL, opis TEXT DEFAULT NULL, ilosc INT NOT NULL, cena NUMERIC(10, 2) NOT NULL, informacjedowyceny TEXT DEFAULT NULL, idkategoria INT DEFAULT NULL, PRIMARY KEY(idsprzet))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_11BC76F98BD319C0 ON magazyn (idkategoria)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE osoby (idosoba INT DEFAULT osoby_idosoba_seq NOT NULL, imie VARCHAR(50) NOT NULL, nazwisko VARCHAR(50) NOT NULL, mail VARCHAR(100) NOT NULL, haslo VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY(idosoba))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX osoby_mail_key ON osoby (mail)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE wycena ADD CONSTRAINT wycena_idfirma_fkey FOREIGN KEY (idfirma) REFERENCES firma (idfirma) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE wycenasprzet ADD CONSTRAINT wycenasprzet_idwycena_fkey FOREIGN KEY (idwycena) REFERENCES wycena (idwycena) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE wycenasprzet ADD CONSTRAINT wycenasprzet_idsprzet_fkey FOREIGN KEY (idsprzet) REFERENCES magazyn (idsprzet) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE magazyn ADD CONSTRAINT magazyn_idkategoria_fkey FOREIGN KEY (idkategoria) REFERENCES kategoria (idkategoria) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE equipment
        SQL);
    }
}
